---
abstract: 'Dochazka ATT system command line client'
author:
  - 'Smithfarm <presnypreklad@gmail.com>'
build_requires:
  App::CELL: '0.209'
  App::Dochazka: '0.189'
  Date::Calc: '0'
  Params::Validate: '1.06'
  Test::Fatal: '0'
  Web::MREST::CLI::UserAgent: '0'
configure_requires:
  Module::Build: '0.37'
  Software::License: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4212, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dochazka-CLI
provides:
  App::Dochazka::CLI:
    file: lib/App/Dochazka/CLI.pm
    version: '0.197'
  App::Dochazka::CLI::CommandMap:
    file: lib/App/Dochazka/CLI/CommandMap.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::Activity:
    file: lib/App/Dochazka/CLI/Commands/Activity.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::Employee:
    file: lib/App/Dochazka/CLI/Commands/Employee.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::History:
    file: lib/App/Dochazka/CLI/Commands/History.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::Interval:
    file: lib/App/Dochazka/CLI/Commands/Interval.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::Misc:
    file: lib/App/Dochazka/CLI/Commands/Misc.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::Priv:
    file: lib/App/Dochazka/CLI/Commands/Priv.pm
    version: '0.197'
  App::Dochazka::CLI::Commands::Schedule:
    file: lib/App/Dochazka/CLI/Commands/Schedule.pm
    version: '0.197'
  App::Dochazka::CLI::Guide:
    file: lib/App/Dochazka/CLI/Guide.pm
    version: '0.197'
  App::Dochazka::CLI::Parser:
    file: lib/App/Dochazka/CLI/Parser.pm
    version: '0.197'
  App::Dochazka::CLI::Shared:
    file: lib/App/Dochazka/CLI/Shared.pm
    version: '0.197'
  App::Dochazka::CLI::Test:
    file: lib/App/Dochazka/CLI/Test.pm
    version: '0.197'
  App::Dochazka::CLI::TokenMap:
    file: lib/App/Dochazka/CLI/TokenMap.pm
    version: '0.197'
  App::Dochazka::CLI::Util:
    file: lib/App/Dochazka/CLI/Util.pm
    version: '0.197'
requires:
  App::CELL: '0.209'
  App::Dochazka: '0.189'
  Date::Calc: '0'
  File::ShareDir: '1.00'
  Getopt::Long: '2.32'
  HTTP::Cookies: '0'
  HTTP::Request: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Params::Validate: '1.06'
  Term::ReadLine::Gnu: '0'
  Text::Table: '0'
  Web::MREST::CLI::UserAgent: '0'
  perl: '5.012'
resources:
  homepage: https://sourceforge.net/projects/dochazka/
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://sourceforge.net/p/dochazka/code/
version: '0.197'
